services:
  - type: web
    name: xpandtb-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn api.app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: VOLUTB_SESI_JAM
        value: 24
